# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
env:
  BUILD_TARGET: DEFAULT
on:
  pull_request:
    paths:
      - 'src/**/*'
      - 'pages/**/*'
      - '.storybook/**/*'
      - 'public/**/*'
      - '.github/workflows/**/*'
      - 'package*.json'
      - 'jest.config.js'
      - 'tsconfig.json'
      - '.eslintrc.json'
      - 'next.config.js'
      - 'create-env.js'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v3
      - name: Set nvmrc for GitHub environment
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV
      - name: Use Node.js "${{ env.NODE_VERSION }}"
        uses: actions/setup-node@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run type-check
      - run: npm run test
